// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: backend/notice/v1/notice.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取公告列表请求
type GetNoticeListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoticeListReq) Reset() {
	*x = GetNoticeListReq{}
	mi := &file_backend_notice_v1_notice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoticeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoticeListReq) ProtoMessage() {}

func (x *GetNoticeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_notice_v1_notice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoticeListReq.ProtoReflect.Descriptor instead.
func (*GetNoticeListReq) Descriptor() ([]byte, []int) {
	return file_backend_notice_v1_notice_proto_rawDescGZIP(), []int{0}
}

func (x *GetNoticeListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetNoticeListReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetNoticeListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetNoticeListReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// 获取公告列表响应
type GetNoticeListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*NoticeItem          `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page"`
	TypeList      []*TypeItem            `protobuf:"bytes,5,rep,name=type_list,json=typeList,proto3" json:"type_list"`
	StatusList    []*StatusItem          `protobuf:"bytes,6,rep,name=status_list,json=statusList,proto3" json:"status_list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoticeListRes) Reset() {
	*x = GetNoticeListRes{}
	mi := &file_backend_notice_v1_notice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoticeListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoticeListRes) ProtoMessage() {}

func (x *GetNoticeListRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_notice_v1_notice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoticeListRes.ProtoReflect.Descriptor instead.
func (*GetNoticeListRes) Descriptor() ([]byte, []int) {
	return file_backend_notice_v1_notice_proto_rawDescGZIP(), []int{1}
}

func (x *GetNoticeListRes) GetList() []*NoticeItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetNoticeListRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetNoticeListRes) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetNoticeListRes) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetNoticeListRes) GetTypeList() []*TypeItem {
	if x != nil {
		return x.TypeList
	}
	return nil
}

func (x *GetNoticeListRes) GetStatusList() []*StatusItem {
	if x != nil {
		return x.StatusList
	}
	return nil
}

// 公告项
type NoticeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type"`
	TypeName      string                 `protobuf:"bytes,5,opt,name=type_name,json=typeName,proto3" json:"type_name"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status"`
	StatusName    string                 `protobuf:"bytes,7,opt,name=status_name,json=statusName,proto3" json:"status_name"`
	Sort          int32                  `protobuf:"varint,8,opt,name=sort,proto3" json:"sort"`
	IsTop         int32                  `protobuf:"varint,9,opt,name=is_top,json=isTop,proto3" json:"is_top"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeItem) Reset() {
	*x = NoticeItem{}
	mi := &file_backend_notice_v1_notice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeItem) ProtoMessage() {}

func (x *NoticeItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_notice_v1_notice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeItem.ProtoReflect.Descriptor instead.
func (*NoticeItem) Descriptor() ([]byte, []int) {
	return file_backend_notice_v1_notice_proto_rawDescGZIP(), []int{2}
}

func (x *NoticeItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NoticeItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoticeItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NoticeItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *NoticeItem) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *NoticeItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *NoticeItem) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *NoticeItem) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *NoticeItem) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *NoticeItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *NoticeItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 类型项
type TypeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeItem) Reset() {
	*x = TypeItem{}
	mi := &file_backend_notice_v1_notice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeItem) ProtoMessage() {}

func (x *TypeItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_notice_v1_notice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeItem.ProtoReflect.Descriptor instead.
func (*TypeItem) Descriptor() ([]byte, []int) {
	return file_backend_notice_v1_notice_proto_rawDescGZIP(), []int{3}
}

func (x *TypeItem) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TypeItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 状态项
type StatusItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusItem) Reset() {
	*x = StatusItem{}
	mi := &file_backend_notice_v1_notice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusItem) ProtoMessage() {}

func (x *StatusItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_notice_v1_notice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusItem.ProtoReflect.Descriptor instead.
func (*StatusItem) Descriptor() ([]byte, []int) {
	return file_backend_notice_v1_notice_proto_rawDescGZIP(), []int{4}
}

func (x *StatusItem) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StatusItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 创建公告请求
type CreateNoticeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title" v:"required|length:2,200"`         // v: required|length:2,200
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content" v:"required|length:2,5000"`    // v: required|length:2,5000
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type" v:"required|in:1,2,3"`              // v: required|in:1,2,3
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status" v:"required|in:0,1"`            // v: required|in:0,1
	Sort          int32                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort" v:"required|min:0"`                 // v: required|min:0
	IsTop         int32                  `protobuf:"varint,6,opt,name=is_top,json=isTop,proto3" json:"is_top" v:"required|in:0,1"` // v: required|in:0,1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoticeReq) Reset() {
	*x = CreateNoticeReq{}
	mi := &file_backend_notice_v1_notice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoticeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoticeReq) ProtoMessage() {}

func (x *CreateNoticeReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_notice_v1_notice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoticeReq.ProtoReflect.Descriptor instead.
func (*CreateNoticeReq) Descriptor() ([]byte, []int) {
	return file_backend_notice_v1_notice_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNoticeReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNoticeReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateNoticeReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateNoticeReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateNoticeReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreateNoticeReq) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

// 创建公告响应
type CreateNoticeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoticeRes) Reset() {
	*x = CreateNoticeRes{}
	mi := &file_backend_notice_v1_notice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoticeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoticeRes) ProtoMessage() {}

func (x *CreateNoticeRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_notice_v1_notice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoticeRes.ProtoReflect.Descriptor instead.
func (*CreateNoticeRes) Descriptor() ([]byte, []int) {
	return file_backend_notice_v1_notice_proto_rawDescGZIP(), []int{6}
}

// 更新公告请求
type UpdateNoticeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" v:"required|min:1"`                     // v: required|min:1
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title" v:"required|length:2,200"`         // v: required|length:2,200
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content" v:"required|length:2,5000"`    // v: required|length:2,5000
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type" v:"required|in:1,2,3"`              // v: required|in:1,2,3
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status" v:"required|in:0,1"`            // v: required|in:0,1
	Sort          int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort" v:"required|min:0"`                 // v: required|min:0
	IsTop         int32                  `protobuf:"varint,7,opt,name=is_top,json=isTop,proto3" json:"is_top" v:"required|in:0,1"` // v: required|in:0,1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoticeReq) Reset() {
	*x = UpdateNoticeReq{}
	mi := &file_backend_notice_v1_notice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoticeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoticeReq) ProtoMessage() {}

func (x *UpdateNoticeReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_notice_v1_notice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoticeReq.ProtoReflect.Descriptor instead.
func (*UpdateNoticeReq) Descriptor() ([]byte, []int) {
	return file_backend_notice_v1_notice_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateNoticeReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateNoticeReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNoticeReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateNoticeReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateNoticeReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateNoticeReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UpdateNoticeReq) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

// 更新公告响应
type UpdateNoticeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoticeRes) Reset() {
	*x = UpdateNoticeRes{}
	mi := &file_backend_notice_v1_notice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoticeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoticeRes) ProtoMessage() {}

func (x *UpdateNoticeRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_notice_v1_notice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoticeRes.ProtoReflect.Descriptor instead.
func (*UpdateNoticeRes) Descriptor() ([]byte, []int) {
	return file_backend_notice_v1_notice_proto_rawDescGZIP(), []int{8}
}

// 删除公告请求
type DeleteNoticeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" v:"required|min:1"` // v: required|min:1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoticeReq) Reset() {
	*x = DeleteNoticeReq{}
	mi := &file_backend_notice_v1_notice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoticeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoticeReq) ProtoMessage() {}

func (x *DeleteNoticeReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_notice_v1_notice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoticeReq.ProtoReflect.Descriptor instead.
func (*DeleteNoticeReq) Descriptor() ([]byte, []int) {
	return file_backend_notice_v1_notice_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteNoticeReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除公告响应
type DeleteNoticeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoticeRes) Reset() {
	*x = DeleteNoticeRes{}
	mi := &file_backend_notice_v1_notice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoticeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoticeRes) ProtoMessage() {}

func (x *DeleteNoticeRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_notice_v1_notice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoticeRes.ProtoReflect.Descriptor instead.
func (*DeleteNoticeRes) Descriptor() ([]byte, []int) {
	return file_backend_notice_v1_notice_proto_rawDescGZIP(), []int{10}
}

var File_backend_notice_v1_notice_proto protoreflect.FileDescriptor

const file_backend_notice_v1_notice_proto_rawDesc = "" +
	"\n" +
	"\x1ebackend/notice/v1/notice.proto\x12\x06notice\"f\n" +
	"\x10GetNoticeListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\"\xf2\x01\n" +
	"\x10GetNoticeListRes\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.notice.NoticeItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\x12-\n" +
	"\ttype_list\x18\x05 \x03(\v2\x10.notice.TypeItemR\btypeList\x123\n" +
	"\vstatus_list\x18\x06 \x03(\v2\x12.notice.StatusItemR\n" +
	"statusList\"\x9f\x02\n" +
	"\n" +
	"NoticeItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x1b\n" +
	"\ttype_name\x18\x05 \x01(\tR\btypeName\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_name\x18\a \x01(\tR\n" +
	"statusName\x12\x12\n" +
	"\x04sort\x18\b \x01(\x05R\x04sort\x12\x15\n" +
	"\x06is_top\x18\t \x01(\x05R\x05isTop\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"4\n" +
	"\bTypeItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"6\n" +
	"\n" +
	"StatusItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x98\x01\n" +
	"\x0fCreateNoticeReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x05R\x04sort\x12\x15\n" +
	"\x06is_top\x18\x06 \x01(\x05R\x05isTop\"\x11\n" +
	"\x0fCreateNoticeRes\"\xa8\x01\n" +
	"\x0fUpdateNoticeReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\x12\x15\n" +
	"\x06is_top\x18\a \x01(\x05R\x05isTop\"\x11\n" +
	"\x0fUpdateNoticeRes\"!\n" +
	"\x0fDeleteNoticeReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x11\n" +
	"\x0fDeleteNoticeRes2\x9b\x02\n" +
	"\x06Notice\x12E\n" +
	"\rGetNoticeList\x12\x18.notice.GetNoticeListReq\x1a\x18.notice.GetNoticeListRes\"\x00\x12B\n" +
	"\fCreateNotice\x12\x17.notice.CreateNoticeReq\x1a\x17.notice.CreateNoticeRes\"\x00\x12B\n" +
	"\fUpdateNotice\x12\x17.notice.UpdateNoticeReq\x1a\x17.notice.UpdateNoticeRes\"\x00\x12B\n" +
	"\fDeleteNotice\x12\x17.notice.DeleteNoticeReq\x1a\x17.notice.DeleteNoticeRes\"\x00B&Z$jh_app_service/api/backend/notice/v1b\x06proto3"

var (
	file_backend_notice_v1_notice_proto_rawDescOnce sync.Once
	file_backend_notice_v1_notice_proto_rawDescData []byte
)

func file_backend_notice_v1_notice_proto_rawDescGZIP() []byte {
	file_backend_notice_v1_notice_proto_rawDescOnce.Do(func() {
		file_backend_notice_v1_notice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_notice_v1_notice_proto_rawDesc), len(file_backend_notice_v1_notice_proto_rawDesc)))
	})
	return file_backend_notice_v1_notice_proto_rawDescData
}

var file_backend_notice_v1_notice_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_backend_notice_v1_notice_proto_goTypes = []any{
	(*GetNoticeListReq)(nil), // 0: notice.GetNoticeListReq
	(*GetNoticeListRes)(nil), // 1: notice.GetNoticeListRes
	(*NoticeItem)(nil),       // 2: notice.NoticeItem
	(*TypeItem)(nil),         // 3: notice.TypeItem
	(*StatusItem)(nil),       // 4: notice.StatusItem
	(*CreateNoticeReq)(nil),  // 5: notice.CreateNoticeReq
	(*CreateNoticeRes)(nil),  // 6: notice.CreateNoticeRes
	(*UpdateNoticeReq)(nil),  // 7: notice.UpdateNoticeReq
	(*UpdateNoticeRes)(nil),  // 8: notice.UpdateNoticeRes
	(*DeleteNoticeReq)(nil),  // 9: notice.DeleteNoticeReq
	(*DeleteNoticeRes)(nil),  // 10: notice.DeleteNoticeRes
}
var file_backend_notice_v1_notice_proto_depIdxs = []int32{
	2,  // 0: notice.GetNoticeListRes.list:type_name -> notice.NoticeItem
	3,  // 1: notice.GetNoticeListRes.type_list:type_name -> notice.TypeItem
	4,  // 2: notice.GetNoticeListRes.status_list:type_name -> notice.StatusItem
	0,  // 3: notice.Notice.GetNoticeList:input_type -> notice.GetNoticeListReq
	5,  // 4: notice.Notice.CreateNotice:input_type -> notice.CreateNoticeReq
	7,  // 5: notice.Notice.UpdateNotice:input_type -> notice.UpdateNoticeReq
	9,  // 6: notice.Notice.DeleteNotice:input_type -> notice.DeleteNoticeReq
	1,  // 7: notice.Notice.GetNoticeList:output_type -> notice.GetNoticeListRes
	6,  // 8: notice.Notice.CreateNotice:output_type -> notice.CreateNoticeRes
	8,  // 9: notice.Notice.UpdateNotice:output_type -> notice.UpdateNoticeRes
	10, // 10: notice.Notice.DeleteNotice:output_type -> notice.DeleteNoticeRes
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_backend_notice_v1_notice_proto_init() }
func file_backend_notice_v1_notice_proto_init() {
	if File_backend_notice_v1_notice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_notice_v1_notice_proto_rawDesc), len(file_backend_notice_v1_notice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_notice_v1_notice_proto_goTypes,
		DependencyIndexes: file_backend_notice_v1_notice_proto_depIdxs,
		MessageInfos:      file_backend_notice_v1_notice_proto_msgTypes,
	}.Build()
	File_backend_notice_v1_notice_proto = out.File
	file_backend_notice_v1_notice_proto_goTypes = nil
	file_backend_notice_v1_notice_proto_depIdxs = nil
}
