// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: backend/message/v1/message.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取消息列表请求
type GetMessageListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageListReq) Reset() {
	*x = GetMessageListReq{}
	mi := &file_backend_message_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageListReq) ProtoMessage() {}

func (x *GetMessageListReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageListReq.ProtoReflect.Descriptor instead.
func (*GetMessageListReq) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *GetMessageListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMessageListReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 获取消息列表响应
type GetMessageListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageList   []*MessageItem         `protobuf:"bytes,1,rep,name=message_list,json=messageList,proto3" json:"message_list"`
	GradeList     []*GradeItem           `protobuf:"bytes,2,rep,name=grade_list,json=gradeList,proto3" json:"grade_list"`
	LevelList     []*LevelItem           `protobuf:"bytes,3,rep,name=level_list,json=levelList,proto3" json:"level_list"`
	StatusList    []*StatusItem          `protobuf:"bytes,4,rep,name=status_list,json=statusList,proto3" json:"status_list"`
	Total         int32                  `protobuf:"varint,5,opt,name=total,proto3" json:"total"`
	CurrentPage   int32                  `protobuf:"varint,6,opt,name=current_page,json=currentPage,proto3" json:"current_page"`
	PerPage       int32                  `protobuf:"varint,7,opt,name=per_page,json=perPage,proto3" json:"per_page"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageListRes) Reset() {
	*x = GetMessageListRes{}
	mi := &file_backend_message_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageListRes) ProtoMessage() {}

func (x *GetMessageListRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageListRes.ProtoReflect.Descriptor instead.
func (*GetMessageListRes) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *GetMessageListRes) GetMessageList() []*MessageItem {
	if x != nil {
		return x.MessageList
	}
	return nil
}

func (x *GetMessageListRes) GetGradeList() []*GradeItem {
	if x != nil {
		return x.GradeList
	}
	return nil
}

func (x *GetMessageListRes) GetLevelList() []*LevelItem {
	if x != nil {
		return x.LevelList
	}
	return nil
}

func (x *GetMessageListRes) GetStatusList() []*StatusItem {
	if x != nil {
		return x.StatusList
	}
	return nil
}

func (x *GetMessageListRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetMessageListRes) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetMessageListRes) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

// 消息项
type MessageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content"`
	Receiver      string                 `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_backend_message_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *MessageItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MessageItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageItem) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *MessageItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MessageItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 等级项
type GradeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeItem) Reset() {
	*x = GradeItem{}
	mi := &file_backend_message_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeItem) ProtoMessage() {}

func (x *GradeItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeItem.ProtoReflect.Descriptor instead.
func (*GradeItem) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *GradeItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GradeItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 层级项
type LevelItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelItem) Reset() {
	*x = LevelItem{}
	mi := &file_backend_message_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelItem) ProtoMessage() {}

func (x *LevelItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelItem.ProtoReflect.Descriptor instead.
func (*LevelItem) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *LevelItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LevelItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 状态项
type StatusItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusItem) Reset() {
	*x = StatusItem{}
	mi := &file_backend_message_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusItem) ProtoMessage() {}

func (x *StatusItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusItem.ProtoReflect.Descriptor instead.
func (*StatusItem) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *StatusItem) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StatusItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 创建消息请求
type CreateMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title" v:"required|length:2,255"`              // v: required|length:2,255
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content" v:"required|length:2,255"`          // v: required|length:2,255
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type" 1:"指定用户 2:等级 3:层级 4:状态"`                 // 1:指定用户 2:等级 3:层级 4:状态
	Receiver      string                 `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver" dc:"接收者（用户名或ID列表）"`               // 接收者（用户名或ID列表）
	GradeId       int32                  `protobuf:"varint,5,opt,name=grade_id,json=gradeId,proto3" json:"grade_id" dc:"等级ID"`          // 等级ID
	LevelId       int32                  `protobuf:"varint,6,opt,name=level_id,json=levelId,proto3" json:"level_id" dc:"层级ID"`          // 层级ID
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status" dc:"状态"`                             // 状态
	Position      int32                  `protobuf:"varint,8,opt,name=position,proto3" json:"position" dc:"弹框位置"`                       // 弹框位置
	AlertTimes    int32                  `protobuf:"varint,9,opt,name=alert_times,json=alertTimes,proto3" json:"alert_times" dc:"弹框次数"` // 弹框次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageReq) Reset() {
	*x = CreateMessageReq{}
	mi := &file_backend_message_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageReq) ProtoMessage() {}

func (x *CreateMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageReq.ProtoReflect.Descriptor instead.
func (*CreateMessageReq) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMessageReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateMessageReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateMessageReq) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *CreateMessageReq) GetGradeId() int32 {
	if x != nil {
		return x.GradeId
	}
	return 0
}

func (x *CreateMessageReq) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *CreateMessageReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateMessageReq) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CreateMessageReq) GetAlertTimes() int32 {
	if x != nil {
		return x.AlertTimes
	}
	return 0
}

// 创建消息响应
type CreateMessageRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageRes) Reset() {
	*x = CreateMessageRes{}
	mi := &file_backend_message_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRes) ProtoMessage() {}

func (x *CreateMessageRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRes.ProtoReflect.Descriptor instead.
func (*CreateMessageRes) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{7}
}

// 获取用户消息请求
type GetUserMessagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMessagesReq) Reset() {
	*x = GetUserMessagesReq{}
	mi := &file_backend_message_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMessagesReq) ProtoMessage() {}

func (x *GetUserMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMessagesReq.ProtoReflect.Descriptor instead.
func (*GetUserMessagesReq) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserMessagesReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserMessagesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserMessagesReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 获取用户消息响应
type GetUserMessagesRes struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	List               []*UserMessageItem     `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total              int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	CurrentPage        int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page"`
	PerPage            int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page"`
	UnreadMessageCount int32                  `protobuf:"varint,5,opt,name=unread_message_count,json=unreadMessageCount,proto3" json:"unread_message_count"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetUserMessagesRes) Reset() {
	*x = GetUserMessagesRes{}
	mi := &file_backend_message_v1_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMessagesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMessagesRes) ProtoMessage() {}

func (x *GetUserMessagesRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMessagesRes.ProtoReflect.Descriptor instead.
func (*GetUserMessagesRes) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserMessagesRes) GetList() []*UserMessageItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetUserMessagesRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetUserMessagesRes) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetUserMessagesRes) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetUserMessagesRes) GetUnreadMessageCount() int32 {
	if x != nil {
		return x.UnreadMessageCount
	}
	return 0
}

// 用户消息项
type UserMessageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content"`
	IsRead        int32                  `protobuf:"varint,4,opt,name=is_read,json=isRead,proto3" json:"is_read"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessageItem) Reset() {
	*x = UserMessageItem{}
	mi := &file_backend_message_v1_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessageItem) ProtoMessage() {}

func (x *UserMessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessageItem.ProtoReflect.Descriptor instead.
func (*UserMessageItem) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{10}
}

func (x *UserMessageItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserMessageItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserMessageItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UserMessageItem) GetIsRead() int32 {
	if x != nil {
		return x.IsRead
	}
	return 0
}

func (x *UserMessageItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 获取未读数量请求
type GetUnreadCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountReq) Reset() {
	*x = GetUnreadCountReq{}
	mi := &file_backend_message_v1_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountReq) ProtoMessage() {}

func (x *GetUnreadCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountReq.ProtoReflect.Descriptor instead.
func (*GetUnreadCountReq) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{11}
}

func (x *GetUnreadCountReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取未读数量响应
type GetUnreadCountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRes) Reset() {
	*x = GetUnreadCountRes{}
	mi := &file_backend_message_v1_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRes) ProtoMessage() {}

func (x *GetUnreadCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRes.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRes) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{12}
}

func (x *GetUnreadCountRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 读取消息请求
type ReadMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	MessageId     int32                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMessageReq) Reset() {
	*x = ReadMessageReq{}
	mi := &file_backend_message_v1_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageReq) ProtoMessage() {}

func (x *ReadMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageReq.ProtoReflect.Descriptor instead.
func (*ReadMessageReq) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{13}
}

func (x *ReadMessageReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReadMessageReq) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// 读取消息响应
type ReadMessageRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMessageRes) Reset() {
	*x = ReadMessageRes{}
	mi := &file_backend_message_v1_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageRes) ProtoMessage() {}

func (x *ReadMessageRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_message_v1_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageRes.ProtoReflect.Descriptor instead.
func (*ReadMessageRes) Descriptor() ([]byte, []int) {
	return file_backend_message_v1_message_proto_rawDescGZIP(), []int{14}
}

var File_backend_message_v1_message_proto protoreflect.FileDescriptor

const file_backend_message_v1_message_proto_rawDesc = "" +
	"\n" +
	" backend/message/v1/message.proto\x12\amessage\";\n" +
	"\x11GetMessageListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\xbc\x02\n" +
	"\x11GetMessageListRes\x127\n" +
	"\fmessage_list\x18\x01 \x03(\v2\x14.message.MessageItemR\vmessageList\x121\n" +
	"\n" +
	"grade_list\x18\x02 \x03(\v2\x12.message.GradeItemR\tgradeList\x121\n" +
	"\n" +
	"level_list\x18\x03 \x03(\v2\x12.message.LevelItemR\tlevelList\x124\n" +
	"\vstatus_list\x18\x04 \x03(\v2\x13.message.StatusItemR\n" +
	"statusList\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\x12!\n" +
	"\fcurrent_page\x18\x06 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bper_page\x18\a \x01(\x05R\aperPage\"\xa7\x01\n" +
	"\vMessageItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\breceiver\x18\x04 \x01(\tR\breceiver\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"/\n" +
	"\tGradeItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"/\n" +
	"\tLevelItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"6\n" +
	"\n" +
	"StatusItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xfd\x01\n" +
	"\x10CreateMessageReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x1a\n" +
	"\breceiver\x18\x04 \x01(\tR\breceiver\x12\x19\n" +
	"\bgrade_id\x18\x05 \x01(\x05R\agradeId\x12\x19\n" +
	"\blevel_id\x18\x06 \x01(\x05R\alevelId\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1a\n" +
	"\bposition\x18\b \x01(\x05R\bposition\x12\x1f\n" +
	"\valert_times\x18\t \x01(\x05R\n" +
	"alertTimes\"\x12\n" +
	"\x10CreateMessageRes\"U\n" +
	"\x12GetUserMessagesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"\xc8\x01\n" +
	"\x12GetUserMessagesRes\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.message.UserMessageItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\x120\n" +
	"\x14unread_message_count\x18\x05 \x01(\x05R\x12unreadMessageCount\"\x89\x01\n" +
	"\x0fUserMessageItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x17\n" +
	"\ais_read\x18\x04 \x01(\x05R\x06isRead\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\",\n" +
	"\x11GetUnreadCountReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\")\n" +
	"\x11GetUnreadCountRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"H\n" +
	"\x0eReadMessageReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x05R\tmessageId\"\x10\n" +
	"\x0eReadMessageRes2\xfc\x02\n" +
	"\aMessage\x12J\n" +
	"\x0eGetMessageList\x12\x1a.message.GetMessageListReq\x1a\x1a.message.GetMessageListRes\"\x00\x12G\n" +
	"\rCreateMessage\x12\x19.message.CreateMessageReq\x1a\x19.message.CreateMessageRes\"\x00\x12M\n" +
	"\x0fGetUserMessages\x12\x1b.message.GetUserMessagesReq\x1a\x1b.message.GetUserMessagesRes\"\x00\x12J\n" +
	"\x0eGetUnreadCount\x12\x1a.message.GetUnreadCountReq\x1a\x1a.message.GetUnreadCountRes\"\x00\x12A\n" +
	"\vReadMessage\x12\x17.message.ReadMessageReq\x1a\x17.message.ReadMessageRes\"\x00B'Z%jh_app_service/api/backend/message/v1b\x06proto3"

var (
	file_backend_message_v1_message_proto_rawDescOnce sync.Once
	file_backend_message_v1_message_proto_rawDescData []byte
)

func file_backend_message_v1_message_proto_rawDescGZIP() []byte {
	file_backend_message_v1_message_proto_rawDescOnce.Do(func() {
		file_backend_message_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_message_v1_message_proto_rawDesc), len(file_backend_message_v1_message_proto_rawDesc)))
	})
	return file_backend_message_v1_message_proto_rawDescData
}

var file_backend_message_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_backend_message_v1_message_proto_goTypes = []any{
	(*GetMessageListReq)(nil),  // 0: message.GetMessageListReq
	(*GetMessageListRes)(nil),  // 1: message.GetMessageListRes
	(*MessageItem)(nil),        // 2: message.MessageItem
	(*GradeItem)(nil),          // 3: message.GradeItem
	(*LevelItem)(nil),          // 4: message.LevelItem
	(*StatusItem)(nil),         // 5: message.StatusItem
	(*CreateMessageReq)(nil),   // 6: message.CreateMessageReq
	(*CreateMessageRes)(nil),   // 7: message.CreateMessageRes
	(*GetUserMessagesReq)(nil), // 8: message.GetUserMessagesReq
	(*GetUserMessagesRes)(nil), // 9: message.GetUserMessagesRes
	(*UserMessageItem)(nil),    // 10: message.UserMessageItem
	(*GetUnreadCountReq)(nil),  // 11: message.GetUnreadCountReq
	(*GetUnreadCountRes)(nil),  // 12: message.GetUnreadCountRes
	(*ReadMessageReq)(nil),     // 13: message.ReadMessageReq
	(*ReadMessageRes)(nil),     // 14: message.ReadMessageRes
}
var file_backend_message_v1_message_proto_depIdxs = []int32{
	2,  // 0: message.GetMessageListRes.message_list:type_name -> message.MessageItem
	3,  // 1: message.GetMessageListRes.grade_list:type_name -> message.GradeItem
	4,  // 2: message.GetMessageListRes.level_list:type_name -> message.LevelItem
	5,  // 3: message.GetMessageListRes.status_list:type_name -> message.StatusItem
	10, // 4: message.GetUserMessagesRes.list:type_name -> message.UserMessageItem
	0,  // 5: message.Message.GetMessageList:input_type -> message.GetMessageListReq
	6,  // 6: message.Message.CreateMessage:input_type -> message.CreateMessageReq
	8,  // 7: message.Message.GetUserMessages:input_type -> message.GetUserMessagesReq
	11, // 8: message.Message.GetUnreadCount:input_type -> message.GetUnreadCountReq
	13, // 9: message.Message.ReadMessage:input_type -> message.ReadMessageReq
	1,  // 10: message.Message.GetMessageList:output_type -> message.GetMessageListRes
	7,  // 11: message.Message.CreateMessage:output_type -> message.CreateMessageRes
	9,  // 12: message.Message.GetUserMessages:output_type -> message.GetUserMessagesRes
	12, // 13: message.Message.GetUnreadCount:output_type -> message.GetUnreadCountRes
	14, // 14: message.Message.ReadMessage:output_type -> message.ReadMessageRes
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_backend_message_v1_message_proto_init() }
func file_backend_message_v1_message_proto_init() {
	if File_backend_message_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_message_v1_message_proto_rawDesc), len(file_backend_message_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_message_v1_message_proto_goTypes,
		DependencyIndexes: file_backend_message_v1_message_proto_depIdxs,
		MessageInfos:      file_backend_message_v1_message_proto_msgTypes,
	}.Build()
	File_backend_message_v1_message_proto = out.File
	file_backend_message_v1_message_proto_goTypes = nil
	file_backend_message_v1_message_proto_depIdxs = nil
}
