// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "jh_admin_service/internal/logic/role"
	_ "jh_admin_service/internal/logic/site"
)
