// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "jh_app_service/internal/logic/backend/admin"
	_ "jh_app_service/internal/logic/backend/role"
	_ "jh_app_service/internal/logic/backend/site"
	_ "jh_app_service/internal/logic/backend/upload"
	_ "jh_app_service/internal/logic/backend/user"
)
