// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: backend/ad/v1/ad.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取广告列表请求
type GetAdListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdListReq) Reset() {
	*x = GetAdListReq{}
	mi := &file_backend_ad_v1_ad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdListReq) ProtoMessage() {}

func (x *GetAdListReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ad_v1_ad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdListReq.ProtoReflect.Descriptor instead.
func (*GetAdListReq) Descriptor() ([]byte, []int) {
	return file_backend_ad_v1_ad_proto_rawDescGZIP(), []int{0}
}

func (x *GetAdListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAdListReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetAdListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetAdListReq) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

// 获取广告列表响应
type GetAdListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AdItem              `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page"`
	PositionList  []*PositionItem        `protobuf:"bytes,5,rep,name=position_list,json=positionList,proto3" json:"position_list"`
	StatusList    []*StatusItem          `protobuf:"bytes,6,rep,name=status_list,json=statusList,proto3" json:"status_list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdListRes) Reset() {
	*x = GetAdListRes{}
	mi := &file_backend_ad_v1_ad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdListRes) ProtoMessage() {}

func (x *GetAdListRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ad_v1_ad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdListRes.ProtoReflect.Descriptor instead.
func (*GetAdListRes) Descriptor() ([]byte, []int) {
	return file_backend_ad_v1_ad_proto_rawDescGZIP(), []int{1}
}

func (x *GetAdListRes) GetList() []*AdItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetAdListRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAdListRes) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetAdListRes) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetAdListRes) GetPositionList() []*PositionItem {
	if x != nil {
		return x.PositionList
	}
	return nil
}

func (x *GetAdListRes) GetStatusList() []*StatusItem {
	if x != nil {
		return x.StatusList
	}
	return nil
}

// 广告项
type AdItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image"`
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position"`
	PositionName  string                 `protobuf:"bytes,6,opt,name=position_name,json=positionName,proto3" json:"position_name"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status"`
	StatusName    string                 `protobuf:"bytes,8,opt,name=status_name,json=statusName,proto3" json:"status_name"`
	Sort          int32                  `protobuf:"varint,9,opt,name=sort,proto3" json:"sort"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdItem) Reset() {
	*x = AdItem{}
	mi := &file_backend_ad_v1_ad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdItem) ProtoMessage() {}

func (x *AdItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ad_v1_ad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdItem.ProtoReflect.Descriptor instead.
func (*AdItem) Descriptor() ([]byte, []int) {
	return file_backend_ad_v1_ad_proto_rawDescGZIP(), []int{2}
}

func (x *AdItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AdItem) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *AdItem) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *AdItem) GetPositionName() string {
	if x != nil {
		return x.PositionName
	}
	return ""
}

func (x *AdItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdItem) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *AdItem) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *AdItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AdItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 位置项
type PositionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionItem) Reset() {
	*x = PositionItem{}
	mi := &file_backend_ad_v1_ad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionItem) ProtoMessage() {}

func (x *PositionItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ad_v1_ad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionItem.ProtoReflect.Descriptor instead.
func (*PositionItem) Descriptor() ([]byte, []int) {
	return file_backend_ad_v1_ad_proto_rawDescGZIP(), []int{3}
}

func (x *PositionItem) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *PositionItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 状态项
type StatusItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusItem) Reset() {
	*x = StatusItem{}
	mi := &file_backend_ad_v1_ad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusItem) ProtoMessage() {}

func (x *StatusItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ad_v1_ad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusItem.ProtoReflect.Descriptor instead.
func (*StatusItem) Descriptor() ([]byte, []int) {
	return file_backend_ad_v1_ad_proto_rawDescGZIP(), []int{4}
}

func (x *StatusItem) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StatusItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 创建广告请求
type CreateAdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title" v:"required|length:2,100"`        // v: required|length:2,100
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image" v:"required"`                     // v: required
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link" v:"required"`                       // v: required
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position" v:"required|in:1,2,3,4,5"` // v: required|in:1,2,3,4,5
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status" v:"required|in:0,1"`           // v: required|in:0,1
	Sort          int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort" v:"required|min:0"`                // v: required|min:0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdReq) Reset() {
	*x = CreateAdReq{}
	mi := &file_backend_ad_v1_ad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdReq) ProtoMessage() {}

func (x *CreateAdReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ad_v1_ad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdReq.ProtoReflect.Descriptor instead.
func (*CreateAdReq) Descriptor() ([]byte, []int) {
	return file_backend_ad_v1_ad_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAdReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAdReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateAdReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CreateAdReq) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CreateAdReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateAdReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

// 创建广告响应
type CreateAdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdRes) Reset() {
	*x = CreateAdRes{}
	mi := &file_backend_ad_v1_ad_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdRes) ProtoMessage() {}

func (x *CreateAdRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ad_v1_ad_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdRes.ProtoReflect.Descriptor instead.
func (*CreateAdRes) Descriptor() ([]byte, []int) {
	return file_backend_ad_v1_ad_proto_rawDescGZIP(), []int{6}
}

// 更新广告请求
type UpdateAdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" v:"required|min:1"`                    // v: required|min:1
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title" v:"required|length:2,100"`        // v: required|length:2,100
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image" v:"required"`                     // v: required
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link" v:"required"`                       // v: required
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position" v:"required|in:1,2,3,4,5"` // v: required|in:1,2,3,4,5
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status" v:"required|in:0,1"`           // v: required|in:0,1
	Sort          int32                  `protobuf:"varint,7,opt,name=sort,proto3" json:"sort" v:"required|min:0"`                // v: required|min:0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdReq) Reset() {
	*x = UpdateAdReq{}
	mi := &file_backend_ad_v1_ad_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdReq) ProtoMessage() {}

func (x *UpdateAdReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ad_v1_ad_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdReq.ProtoReflect.Descriptor instead.
func (*UpdateAdReq) Descriptor() ([]byte, []int) {
	return file_backend_ad_v1_ad_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAdReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAdReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateAdReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *UpdateAdReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *UpdateAdReq) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *UpdateAdReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateAdReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

// 更新广告响应
type UpdateAdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdRes) Reset() {
	*x = UpdateAdRes{}
	mi := &file_backend_ad_v1_ad_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdRes) ProtoMessage() {}

func (x *UpdateAdRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ad_v1_ad_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdRes.ProtoReflect.Descriptor instead.
func (*UpdateAdRes) Descriptor() ([]byte, []int) {
	return file_backend_ad_v1_ad_proto_rawDescGZIP(), []int{8}
}

// 删除广告请求
type DeleteAdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" v:"required|min:1"` // v: required|min:1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdReq) Reset() {
	*x = DeleteAdReq{}
	mi := &file_backend_ad_v1_ad_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdReq) ProtoMessage() {}

func (x *DeleteAdReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ad_v1_ad_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdReq.ProtoReflect.Descriptor instead.
func (*DeleteAdReq) Descriptor() ([]byte, []int) {
	return file_backend_ad_v1_ad_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAdReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除广告响应
type DeleteAdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdRes) Reset() {
	*x = DeleteAdRes{}
	mi := &file_backend_ad_v1_ad_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdRes) ProtoMessage() {}

func (x *DeleteAdRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ad_v1_ad_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdRes.ProtoReflect.Descriptor instead.
func (*DeleteAdRes) Descriptor() ([]byte, []int) {
	return file_backend_ad_v1_ad_proto_rawDescGZIP(), []int{10}
}

var File_backend_ad_v1_ad_proto protoreflect.FileDescriptor

const file_backend_ad_v1_ad_proto_rawDesc = "" +
	"\n" +
	"\x16backend/ad/v1/ad.proto\x12\x02ad\"j\n" +
	"\fGetAdListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\"\xea\x01\n" +
	"\fGetAdListRes\x12\x1e\n" +
	"\x04list\x18\x01 \x03(\v2\n" +
	".ad.AdItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\x125\n" +
	"\rposition_list\x18\x05 \x03(\v2\x10.ad.PositionItemR\fpositionList\x12/\n" +
	"\vstatus_list\x18\x06 \x03(\v2\x0e.ad.StatusItemR\n" +
	"statusList\"\xa4\x02\n" +
	"\x06AdItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x12#\n" +
	"\rposition_name\x18\x06 \x01(\tR\fpositionName\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_name\x18\b \x01(\tR\n" +
	"statusName\x12\x12\n" +
	"\x04sort\x18\t \x01(\x05R\x04sort\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"8\n" +
	"\fPositionItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"6\n" +
	"\n" +
	"StatusItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x95\x01\n" +
	"\vCreateAdReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\"\r\n" +
	"\vCreateAdRes\"\xa5\x01\n" +
	"\vUpdateAdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x12\n" +
	"\x04sort\x18\a \x01(\x05R\x04sort\"\r\n" +
	"\vUpdateAdRes\"\x1d\n" +
	"\vDeleteAdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\r\n" +
	"\vDeleteAdRes2\xc7\x01\n" +
	"\x02Ad\x121\n" +
	"\tGetAdList\x12\x10.ad.GetAdListReq\x1a\x10.ad.GetAdListRes\"\x00\x12.\n" +
	"\bCreateAd\x12\x0f.ad.CreateAdReq\x1a\x0f.ad.CreateAdRes\"\x00\x12.\n" +
	"\bUpdateAd\x12\x0f.ad.UpdateAdReq\x1a\x0f.ad.UpdateAdRes\"\x00\x12.\n" +
	"\bDeleteAd\x12\x0f.ad.DeleteAdReq\x1a\x0f.ad.DeleteAdRes\"\x00B\"Z jh_app_service/api/backend/ad/v1b\x06proto3"

var (
	file_backend_ad_v1_ad_proto_rawDescOnce sync.Once
	file_backend_ad_v1_ad_proto_rawDescData []byte
)

func file_backend_ad_v1_ad_proto_rawDescGZIP() []byte {
	file_backend_ad_v1_ad_proto_rawDescOnce.Do(func() {
		file_backend_ad_v1_ad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_ad_v1_ad_proto_rawDesc), len(file_backend_ad_v1_ad_proto_rawDesc)))
	})
	return file_backend_ad_v1_ad_proto_rawDescData
}

var file_backend_ad_v1_ad_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_backend_ad_v1_ad_proto_goTypes = []any{
	(*GetAdListReq)(nil), // 0: ad.GetAdListReq
	(*GetAdListRes)(nil), // 1: ad.GetAdListRes
	(*AdItem)(nil),       // 2: ad.AdItem
	(*PositionItem)(nil), // 3: ad.PositionItem
	(*StatusItem)(nil),   // 4: ad.StatusItem
	(*CreateAdReq)(nil),  // 5: ad.CreateAdReq
	(*CreateAdRes)(nil),  // 6: ad.CreateAdRes
	(*UpdateAdReq)(nil),  // 7: ad.UpdateAdReq
	(*UpdateAdRes)(nil),  // 8: ad.UpdateAdRes
	(*DeleteAdReq)(nil),  // 9: ad.DeleteAdReq
	(*DeleteAdRes)(nil),  // 10: ad.DeleteAdRes
}
var file_backend_ad_v1_ad_proto_depIdxs = []int32{
	2,  // 0: ad.GetAdListRes.list:type_name -> ad.AdItem
	3,  // 1: ad.GetAdListRes.position_list:type_name -> ad.PositionItem
	4,  // 2: ad.GetAdListRes.status_list:type_name -> ad.StatusItem
	0,  // 3: ad.Ad.GetAdList:input_type -> ad.GetAdListReq
	5,  // 4: ad.Ad.CreateAd:input_type -> ad.CreateAdReq
	7,  // 5: ad.Ad.UpdateAd:input_type -> ad.UpdateAdReq
	9,  // 6: ad.Ad.DeleteAd:input_type -> ad.DeleteAdReq
	1,  // 7: ad.Ad.GetAdList:output_type -> ad.GetAdListRes
	6,  // 8: ad.Ad.CreateAd:output_type -> ad.CreateAdRes
	8,  // 9: ad.Ad.UpdateAd:output_type -> ad.UpdateAdRes
	10, // 10: ad.Ad.DeleteAd:output_type -> ad.DeleteAdRes
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_backend_ad_v1_ad_proto_init() }
func file_backend_ad_v1_ad_proto_init() {
	if File_backend_ad_v1_ad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_ad_v1_ad_proto_rawDesc), len(file_backend_ad_v1_ad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_ad_v1_ad_proto_goTypes,
		DependencyIndexes: file_backend_ad_v1_ad_proto_depIdxs,
		MessageInfos:      file_backend_ad_v1_ad_proto_msgTypes,
	}.Build()
	File_backend_ad_v1_ad_proto = out.File
	file_backend_ad_v1_ad_proto_goTypes = nil
	file_backend_ad_v1_ad_proto_depIdxs = nil
}
