// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: backend/ad/v1/ad.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ad_GetAdList_FullMethodName = "/ad.Ad/GetAdList"
	Ad_CreateAd_FullMethodName  = "/ad.Ad/CreateAd"
	Ad_UpdateAd_FullMethodName  = "/ad.Ad/UpdateAd"
	Ad_DeleteAd_FullMethodName  = "/ad.Ad/DeleteAd"
)

// AdClient is the client API for Ad service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdClient interface {
	GetAdList(ctx context.Context, in *GetAdListReq, opts ...grpc.CallOption) (*GetAdListRes, error)
	CreateAd(ctx context.Context, in *CreateAdReq, opts ...grpc.CallOption) (*CreateAdRes, error)
	UpdateAd(ctx context.Context, in *UpdateAdReq, opts ...grpc.CallOption) (*UpdateAdRes, error)
	DeleteAd(ctx context.Context, in *DeleteAdReq, opts ...grpc.CallOption) (*DeleteAdRes, error)
}

type adClient struct {
	cc grpc.ClientConnInterface
}

func NewAdClient(cc grpc.ClientConnInterface) AdClient {
	return &adClient{cc}
}

func (c *adClient) GetAdList(ctx context.Context, in *GetAdListReq, opts ...grpc.CallOption) (*GetAdListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdListRes)
	err := c.cc.Invoke(ctx, Ad_GetAdList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adClient) CreateAd(ctx context.Context, in *CreateAdReq, opts ...grpc.CallOption) (*CreateAdRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdRes)
	err := c.cc.Invoke(ctx, Ad_CreateAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adClient) UpdateAd(ctx context.Context, in *UpdateAdReq, opts ...grpc.CallOption) (*UpdateAdRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdRes)
	err := c.cc.Invoke(ctx, Ad_UpdateAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adClient) DeleteAd(ctx context.Context, in *DeleteAdReq, opts ...grpc.CallOption) (*DeleteAdRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAdRes)
	err := c.cc.Invoke(ctx, Ad_DeleteAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdServer is the server API for Ad service.
// All implementations must embed UnimplementedAdServer
// for forward compatibility.
type AdServer interface {
	GetAdList(context.Context, *GetAdListReq) (*GetAdListRes, error)
	CreateAd(context.Context, *CreateAdReq) (*CreateAdRes, error)
	UpdateAd(context.Context, *UpdateAdReq) (*UpdateAdRes, error)
	DeleteAd(context.Context, *DeleteAdReq) (*DeleteAdRes, error)
	mustEmbedUnimplementedAdServer()
}

// UnimplementedAdServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdServer struct{}

func (UnimplementedAdServer) GetAdList(context.Context, *GetAdListReq) (*GetAdListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdList not implemented")
}
func (UnimplementedAdServer) CreateAd(context.Context, *CreateAdReq) (*CreateAdRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAd not implemented")
}
func (UnimplementedAdServer) UpdateAd(context.Context, *UpdateAdReq) (*UpdateAdRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAd not implemented")
}
func (UnimplementedAdServer) DeleteAd(context.Context, *DeleteAdReq) (*DeleteAdRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAd not implemented")
}
func (UnimplementedAdServer) mustEmbedUnimplementedAdServer() {}
func (UnimplementedAdServer) testEmbeddedByValue()            {}

// UnsafeAdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdServer will
// result in compilation errors.
type UnsafeAdServer interface {
	mustEmbedUnimplementedAdServer()
}

func RegisterAdServer(s grpc.ServiceRegistrar, srv AdServer) {
	// If the following call panics, it indicates UnimplementedAdServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ad_ServiceDesc, srv)
}

func _Ad_GetAdList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServer).GetAdList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ad_GetAdList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServer).GetAdList(ctx, req.(*GetAdListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ad_CreateAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServer).CreateAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ad_CreateAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServer).CreateAd(ctx, req.(*CreateAdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ad_UpdateAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServer).UpdateAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ad_UpdateAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServer).UpdateAd(ctx, req.(*UpdateAdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ad_DeleteAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServer).DeleteAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ad_DeleteAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServer).DeleteAd(ctx, req.(*DeleteAdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Ad_ServiceDesc is the grpc.ServiceDesc for Ad service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ad_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ad.Ad",
	HandlerType: (*AdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdList",
			Handler:    _Ad_GetAdList_Handler,
		},
		{
			MethodName: "CreateAd",
			Handler:    _Ad_CreateAd_Handler,
		},
		{
			MethodName: "UpdateAd",
			Handler:    _Ad_UpdateAd_Handler,
		},
		{
			MethodName: "DeleteAd",
			Handler:    _Ad_DeleteAd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/ad/v1/ad.proto",
}
