// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: backend/option/v1/option.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Option_GetUserGradeList_FullMethodName = "/option.Option/GetUserGradeList"
	Option_GetAdminRoleList_FullMethodName = "/option.Option/GetAdminRoleList"
)

// OptionClient is the client API for Option service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 选项服务
type OptionClient interface {
	// 获取会员等级列表
	GetUserGradeList(ctx context.Context, in *UserGradeListRequest, opts ...grpc.CallOption) (*UserGradeListResponse, error)
	// 获取后台角色列表
	GetAdminRoleList(ctx context.Context, in *AdminRoleListRequest, opts ...grpc.CallOption) (*AdminRoleListResponse, error)
}

type optionClient struct {
	cc grpc.ClientConnInterface
}

func NewOptionClient(cc grpc.ClientConnInterface) OptionClient {
	return &optionClient{cc}
}

func (c *optionClient) GetUserGradeList(ctx context.Context, in *UserGradeListRequest, opts ...grpc.CallOption) (*UserGradeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGradeListResponse)
	err := c.cc.Invoke(ctx, Option_GetUserGradeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optionClient) GetAdminRoleList(ctx context.Context, in *AdminRoleListRequest, opts ...grpc.CallOption) (*AdminRoleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRoleListResponse)
	err := c.cc.Invoke(ctx, Option_GetAdminRoleList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptionServer is the server API for Option service.
// All implementations must embed UnimplementedOptionServer
// for forward compatibility.
//
// 选项服务
type OptionServer interface {
	// 获取会员等级列表
	GetUserGradeList(context.Context, *UserGradeListRequest) (*UserGradeListResponse, error)
	// 获取后台角色列表
	GetAdminRoleList(context.Context, *AdminRoleListRequest) (*AdminRoleListResponse, error)
	mustEmbedUnimplementedOptionServer()
}

// UnimplementedOptionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOptionServer struct{}

func (UnimplementedOptionServer) GetUserGradeList(context.Context, *UserGradeListRequest) (*UserGradeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserGradeList not implemented")
}
func (UnimplementedOptionServer) GetAdminRoleList(context.Context, *AdminRoleListRequest) (*AdminRoleListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminRoleList not implemented")
}
func (UnimplementedOptionServer) mustEmbedUnimplementedOptionServer() {}
func (UnimplementedOptionServer) testEmbeddedByValue()                {}

// UnsafeOptionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptionServer will
// result in compilation errors.
type UnsafeOptionServer interface {
	mustEmbedUnimplementedOptionServer()
}

func RegisterOptionServer(s grpc.ServiceRegistrar, srv OptionServer) {
	// If the following call panics, it indicates UnimplementedOptionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Option_ServiceDesc, srv)
}

func _Option_GetUserGradeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGradeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptionServer).GetUserGradeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Option_GetUserGradeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptionServer).GetUserGradeList(ctx, req.(*UserGradeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Option_GetAdminRoleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRoleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptionServer).GetAdminRoleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Option_GetAdminRoleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptionServer).GetAdminRoleList(ctx, req.(*AdminRoleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Option_ServiceDesc is the grpc.ServiceDesc for Option service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Option_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "option.Option",
	HandlerType: (*OptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserGradeList",
			Handler:    _Option_GetUserGradeList_Handler,
		},
		{
			MethodName: "GetAdminRoleList",
			Handler:    _Option_GetAdminRoleList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/option/v1/option.proto",
}
