// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: backend/option/v1/option.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 会员等级信息
type UserGrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGrade) Reset() {
	*x = UserGrade{}
	mi := &file_backend_option_v1_option_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGrade) ProtoMessage() {}

func (x *UserGrade) ProtoReflect() protoreflect.Message {
	mi := &file_backend_option_v1_option_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGrade.ProtoReflect.Descriptor instead.
func (*UserGrade) Descriptor() ([]byte, []int) {
	return file_backend_option_v1_option_proto_rawDescGZIP(), []int{0}
}

func (x *UserGrade) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserGrade) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserGrade) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UserGrade) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 后台角色信息
type AdminRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRole) Reset() {
	*x = AdminRole{}
	mi := &file_backend_option_v1_option_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRole) ProtoMessage() {}

func (x *AdminRole) ProtoReflect() protoreflect.Message {
	mi := &file_backend_option_v1_option_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRole.ProtoReflect.Descriptor instead.
func (*AdminRole) Descriptor() ([]byte, []int) {
	return file_backend_option_v1_option_proto_rawDescGZIP(), []int{1}
}

func (x *AdminRole) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminRole) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 会员等级列表请求
type UserGradeListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGradeListRequest) Reset() {
	*x = UserGradeListRequest{}
	mi := &file_backend_option_v1_option_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGradeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGradeListRequest) ProtoMessage() {}

func (x *UserGradeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_option_v1_option_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGradeListRequest.ProtoReflect.Descriptor instead.
func (*UserGradeListRequest) Descriptor() ([]byte, []int) {
	return file_backend_option_v1_option_proto_rawDescGZIP(), []int{2}
}

// 会员等级列表响应 - 直接返回数组
type UserGradeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grades        []*UserGrade           `protobuf:"bytes,1,rep,name=grades,proto3" json:"grades"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGradeListResponse) Reset() {
	*x = UserGradeListResponse{}
	mi := &file_backend_option_v1_option_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGradeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGradeListResponse) ProtoMessage() {}

func (x *UserGradeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_option_v1_option_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGradeListResponse.ProtoReflect.Descriptor instead.
func (*UserGradeListResponse) Descriptor() ([]byte, []int) {
	return file_backend_option_v1_option_proto_rawDescGZIP(), []int{3}
}

func (x *UserGradeListResponse) GetGrades() []*UserGrade {
	if x != nil {
		return x.Grades
	}
	return nil
}

// 后台角色列表请求
type AdminRoleListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRoleListRequest) Reset() {
	*x = AdminRoleListRequest{}
	mi := &file_backend_option_v1_option_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRoleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRoleListRequest) ProtoMessage() {}

func (x *AdminRoleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_option_v1_option_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRoleListRequest.ProtoReflect.Descriptor instead.
func (*AdminRoleListRequest) Descriptor() ([]byte, []int) {
	return file_backend_option_v1_option_proto_rawDescGZIP(), []int{4}
}

// 后台角色列表响应 - 直接返回数组
type AdminRoleListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*AdminRole           `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRoleListResponse) Reset() {
	*x = AdminRoleListResponse{}
	mi := &file_backend_option_v1_option_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRoleListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRoleListResponse) ProtoMessage() {}

func (x *AdminRoleListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_option_v1_option_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRoleListResponse.ProtoReflect.Descriptor instead.
func (*AdminRoleListResponse) Descriptor() ([]byte, []int) {
	return file_backend_option_v1_option_proto_rawDescGZIP(), []int{5}
}

func (x *AdminRoleListResponse) GetRoles() []*AdminRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_backend_option_v1_option_proto protoreflect.FileDescriptor

const file_backend_option_v1_option_proto_rawDesc = "" +
	"\n" +
	"\x1ebackend/option/v1/option.proto\x12\x06option\"[\n" +
	"\tUserGrade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"i\n" +
	"\tAdminRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\x16\n" +
	"\x14UserGradeListRequest\"B\n" +
	"\x15UserGradeListResponse\x12)\n" +
	"\x06grades\x18\x01 \x03(\v2\x11.option.UserGradeR\x06grades\"\x16\n" +
	"\x14AdminRoleListRequest\"@\n" +
	"\x15AdminRoleListResponse\x12'\n" +
	"\x05roles\x18\x01 \x03(\v2\x11.option.AdminRoleR\x05roles2\xaa\x01\n" +
	"\x06Option\x12O\n" +
	"\x10GetUserGradeList\x12\x1c.option.UserGradeListRequest\x1a\x1d.option.UserGradeListResponse\x12O\n" +
	"\x10GetAdminRoleList\x12\x1c.option.AdminRoleListRequest\x1a\x1d.option.AdminRoleListResponseB)Z'jh_app_service/api/backend/option/v1;v1b\x06proto3"

var (
	file_backend_option_v1_option_proto_rawDescOnce sync.Once
	file_backend_option_v1_option_proto_rawDescData []byte
)

func file_backend_option_v1_option_proto_rawDescGZIP() []byte {
	file_backend_option_v1_option_proto_rawDescOnce.Do(func() {
		file_backend_option_v1_option_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_option_v1_option_proto_rawDesc), len(file_backend_option_v1_option_proto_rawDesc)))
	})
	return file_backend_option_v1_option_proto_rawDescData
}

var file_backend_option_v1_option_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_backend_option_v1_option_proto_goTypes = []any{
	(*UserGrade)(nil),             // 0: option.UserGrade
	(*AdminRole)(nil),             // 1: option.AdminRole
	(*UserGradeListRequest)(nil),  // 2: option.UserGradeListRequest
	(*UserGradeListResponse)(nil), // 3: option.UserGradeListResponse
	(*AdminRoleListRequest)(nil),  // 4: option.AdminRoleListRequest
	(*AdminRoleListResponse)(nil), // 5: option.AdminRoleListResponse
}
var file_backend_option_v1_option_proto_depIdxs = []int32{
	0, // 0: option.UserGradeListResponse.grades:type_name -> option.UserGrade
	1, // 1: option.AdminRoleListResponse.roles:type_name -> option.AdminRole
	2, // 2: option.Option.GetUserGradeList:input_type -> option.UserGradeListRequest
	4, // 3: option.Option.GetAdminRoleList:input_type -> option.AdminRoleListRequest
	3, // 4: option.Option.GetUserGradeList:output_type -> option.UserGradeListResponse
	5, // 5: option.Option.GetAdminRoleList:output_type -> option.AdminRoleListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_backend_option_v1_option_proto_init() }
func file_backend_option_v1_option_proto_init() {
	if File_backend_option_v1_option_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_option_v1_option_proto_rawDesc), len(file_backend_option_v1_option_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_option_v1_option_proto_goTypes,
		DependencyIndexes: file_backend_option_v1_option_proto_depIdxs,
		MessageInfos:      file_backend_option_v1_option_proto_msgTypes,
	}.Build()
	File_backend_option_v1_option_proto = out.File
	file_backend_option_v1_option_proto_goTypes = nil
	file_backend_option_v1_option_proto_depIdxs = nil
}
