// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// siteDomainSourceDao is the data access object for the table site_domain_source.
// You can define custom methods on it to extend its functionality as needed.
type siteDomainSourceDao struct {
	*internal.SiteDomainSourceDao
}

var (
	// SiteDomainSource is a globally accessible object for table site_domain_source operations.
	SiteDomainSource = siteDomainSourceDao{internal.NewSiteDomainSourceDao()}
)

// Add your custom methods and functionality below.
